### PR TITLE
Create tutorial input options

### PR DESCRIPTION
**Pull request by kbarnhart**
This is under progress and not yet ready for review. When done it will address #8.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen and @gregtucker could you take a look at the new notebook. Its designed to highlight how to use umami with data/models (e.g., numpy arrays of any sort) that are not from terrainbento or Landlab. 

The following is a binder link for it (specific to this branch). [Binder](https://mybinder.org/v2/gh/TerrainBento/umami/barnhark/other_io_examples?filepath=notebooks%2FOtherIO_options.ipynb)

**Comment by kbarnhart** [comment]
@mcflugen any recommendations for the CI tests. I'm getting the following error on half of the AppVeyor tests:

```bash
pytest -vvv
707ImportError while loading conftest 'C:\projects\umami\tests\conftest.py'.
708tests\conftest.py:3: in <module>
709    from landlab import RasterModelGrid
710c:\miniconda37-x64\lib\site-packages\landlab\__init__.py:29: in <module>
711    from .grid import (
712c:\miniconda37-x64\lib\site-packages\landlab\grid\__init__.py:13: in <module>
713    from .create import create_and_initialize_grid, create_grid
714c:\miniconda37-x64\lib\site-packages\landlab\grid\create.py:8: in <module>
715    from ..io import read_esri_ascii
716c:\miniconda37-x64\lib\site-packages\landlab\io\__init__.py:17: in <module>
717    from .shapefile import read_shapefile
718c:\miniconda37-x64\lib\site-packages\landlab\io\shapefile\__init__.py:1: in <module>
719    from .read_shapefile import read_shapefile
720c:\miniconda37-x64\lib\site-packages\landlab\io\shapefile\read_shapefile.py:9: in <module>
721    from landlab.grid.network import NetworkModelGrid
722c:\miniconda37-x64\lib\site-packages\landlab\grid\network.py:13: in <module>
723    from ..graph import NetworkGraph
724c:\miniconda37-x64\lib\site-packages\landlab\graph\__init__.py:1: in <module>
725    from .dual import DualGraph
726c:\miniconda37-x64\lib\site-packages\landlab\graph\dual.py:11: in <module>
727    from .graph import Graph, find_perimeter_nodes
728c:\miniconda37-x64\lib\site-packages\landlab\graph\graph.py:69: in <module>
729    from .object.at_patch import get_nodes_at_patch
730c:\miniconda37-x64\lib\site-packages\landlab\graph\object\at_patch.py:3: in <module>
731    from .ext.at_patch import get_nodes_at_patch as _get_nodes_at_patch
732__init__.pxd:918: in init landlab.graph.object.ext.at_patch
733    ???
734E   ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
735Command exited with code 4
```

I'm pretty befuddled.

**Comment by mcflugen** [comment]
@kbarnhart 🤔 That is rather befuddling!

For your CI you install *landlab* (and the rest of your dependencies) from PyPI. We haven't really taken much care in making sure the *landlab* wheels we upload to PyPI for Windows are robust. Perhaps there is some kind of incompatibility with one of the wheels that's on PyPI? I wonder if it would help if you were to install *landlab* from *conda-forge* for your AppVeyor builds.

**Comment by kbarnhart** [comment]
@mcflugen Thanks for that recommendation. That fixed it. 

@mcflugen @gregtucker can you let me know what you think about the new tutorial. 

Interactive notebook here: [Binder](https://mybinder.org/v2/gh/TerrainBento/umami/barnhark/other_io_examples?filepath=notebooks%2FOtherIO_options.ipynb)

**Pull request merged**
