### PR TITLE
Barnhark/fix dakota error

### PR DESCRIPTION
**Pull request by kbarnhart**

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen I'm getting some PC only errors from deep within landlab.graph

```
ZeroDivisionError                         Traceback (most recent call last)
1125<ipython-input-14-d0b2009ba193> in <module>
1126----> 1 vdg = VoronoiDelaunayGrid(random_x, random_y)
1127      2 z = vdg.add_field("topographic__elevation", interp_z, at="node")
1128      3 
1129      4 imshow_grid(vdg, z, cmap="terrain")
1130
1131c:\miniconda37-x64\lib\site-packages\landlab\grid\voronoi.py in __init__(self, x, y, reorient_links, xy_of_reference, xy_axis_name, xy_axis_units)
1132    154         25
1133    155         """
1134--> 156         DualVoronoiGraph.__init__(self, (y, x), sort=True)
1135    157         ModelGrid.__init__(
1136    158             self,
1137
1138c:\miniconda37-x64\lib\site-packages\landlab\graph\voronoi\dual_voronoi.py in __init__(self, node_y_and_x, max_node_spacing, sort, perimeter_links)
1139     70 
1140     71         if sort:
1141---> 72             self.sort()
1142
1143c:\miniconda37-x64\lib\site-packages\landlab\graph\dual.py in sort(self)
1144     92         from .sort.ext.remap_element import remap_graph_element
1145     93 
1146---> 94         sorted_nodes, sorted_links, sorted_patches = Graph.sort(self)
1147     95         sorted_corners, sorted_faces, sorted_cells = self.dual.sort()
1148     96 
1149
1150c:\miniconda37-x64\lib\site-packages\landlab\graph\graph.py in sort(self)
1151    799         with self.thawed():
1152    800             reorient_link_dirs(self)
1153--> 801             sorted_nodes, sorted_links, sorted_patches = reindex_by_xy(self)
1154    802             # reorder_links_at_patch(self)
1155    803             if "links_at_patch" in self.ds:
1156
1157c:\miniconda37-x64\lib\site-packages\landlab\graph\sort\sort.py in reindex_by_xy(graph)
1158    210 
1159    211     if "links_at_patch" in graph.ds:
1160--> 212         sorted_patches = reindex_patches_by_xy(graph)
1161    213     else:
1162    214         sorted_patches = None
1163
1164c:\miniconda37-x64\lib\site-packages\landlab\graph\sort\sort.py in reindex_patches_by_xy(graph)
1165    223         return np.array([0], dtype=int)
1166    224 
1167--> 225     xy_at_patch = get_centroid_of_patch(graph)
1168    226 
1169    227     y = xy_at_patch[:, 1]
1170
1171c:\miniconda37-x64\lib\site-packages\landlab\graph\quantity\of_patch.py in get_centroid_of_patch(graph, out)
1172     41         # np.ascontiguousarray(graph.x_of_node),
1173     42         # np.ascontiguousarray(graph.y_of_node),
1174---> 43         out,
1175     44     )
1176     45 
1177
1178landlab\graph\quantity\ext\of_patch.pyx in landlab.graph.quantity.ext.of_patch.calc_centroid_at_patch()
1179
1180landlab\graph\quantity\ext\of_patch.pyx in landlab.graph.quantity.ext.of_patch.calc_centroid_of_patch()
1181
1182landlab\graph\quantity\ext\of_patch.pyx in landlab.graph.quantity.ext.of_patch.calc_centroid_of_polygon()
1183
1184ZeroDivisionError: float division
1185ZeroDivisionError: float division
1186
1187============ 1 failed, 36 passed, 57 warnings in 459.88s (0:07:39) ============
1188
``` 

Any thoughts on why/how to address?

**Comment by mcflugen** [comment]
@kbarnhart I'm not totally sure, however, it appears that one of the patches (or maybe cells) has zero area. This would be caused by its vertices being colinear.

**Comment by kbarnhart** [comment]
Oddly, the issue is only on PCs, I set the seed, and I worked to make the vertices not collinear... but I suspect you are right... will work on fixing. Thanks!

**Comment by mcflugen** [comment]
@kbarnhart when we create a landab *ModelGrid* we round each node's [*y* coordinate](https://github.com/landlab/landlab/blob/1d86db63a3a73b2a5e39aaf2692b6e21881c7737/landlab/graph/sort/sort.py#L269) so that the nodes are sorted as you would expect. Without the rounding, what would happen is that you would sometimes have a "row" of nodes with *(x, y)* coordinates of, for example,
```
(0, 0), (1, 0), (2, 0.000000001), (3, 0)
```
which would then be numbered 0, 1, 3, 2, rather than 0, 1, 2, 3, as they should be. I believe this would most often happen with radial and/or hex grids (since their coordinates are calculated using trig functions).

I don't know, but this might be a cause of points becoming colinear. This may also be the cause of the error you identified in another issue, which I can't find right now.

**Comment by kbarnhart** [comment]
@mcflugen thanks! I just switched this so that I accomplished the same effect using a HexModelGrid...

**Comment by kbarnhart** [comment]
@mcflugen now I'm getting a very strange error. On the Py37 builds only they fail as part of installation with 

Verifying transaction: ...working... done
Executing transaction: ...working... done
The batch file cannot be found.

https://ci.appveyor.com/project/kbarnhart/umami/builds/31057216

This might just be a temporary appveyor blip... but in case it rings a bell for you...LMK

**Comment by mcflugen** [comment]
@mcflugen Sorry, I don't recognize that error. However, when we added Python 3.8 builds on *landlab*, I changed how we built *landlab* on AppVeyor. Maybe copying the current *appveyor.yml* would help?

**Comment by kbarnhart** [comment]
@mcflugen help...?

I have this *almost* working (appveyor is what is broken). 

I updated to be pretty similar to the new landlab approach. But I do need conda for one package... (I tried pip but it just doesn't do the dependencies quite right). 

I've tried a variety of small changes that I thought would fix the CI... but no avail. Any recommendations? THANK YOU!

**Comment by mcflugen** [comment]
@kbarnhart sorry, I don't have any ideas at the moment. 😞  I'll have a look at this tomorrow on the our Windows machine to see if I can reproduce the problem (and fix it?🤞).

**Comment by kbarnhart** [comment]
thank you thank you thank you @mcflugen!

**Comment by mcflugen** [comment]
@kbarnhart I was finally able to install *umami* and run all the tests on our Windows machine. However, I had to install everything from *conda-forge*. If I used a mixture of *PyPI* and *conda-forge* I would get strange errors like, for example, not being able to find *win32api* when running the notebooks.

Anyway, these were the steps I took,
```bash
$ conda create -n umami python
$ conda activate umami
$ conda install numpy statsmodels landlab terrainbento twine pytest pytest-cov pytest-datadir rasterio -c conda-forge
$ conda install jupyter pandas plotnine holoviews tqdm -c conda-forge
$ pip install -e .
$ pytest -vvv
```

**Comment by kbarnhart** [comment]
Thanks @mcflugen! I'll implement this.

**Comment by mcflugen** [comment]
@kbarnhart It looks like things are building again but I think all the builds are with Python 3.8 since I haven't specified the Python version to install. When we add in the Python version to install, I wonder if we'll end up back where we started (with that weird Python 3.7 error)?

**Pull request merged**
